### ISSUE TITLE
discontinued?

### ISSUE THREAD

**Issue by ghost** [robske110/TicTacToe#13]
is this plugin discontinued ?

**Comment by robske110** [comment]
No, not really. What are you missing?

**Comment by ghost** [comment]
@robske110 the plugin doesn't remove the player from the queue when he changes his level or dies or by a command, if u join the queue then go to another game then another player joins the queue it teleports both of u to the arena position even if you are inside a diffrent game , this way games will be ruined and glitches will show up

**Comment by ghost** [comment]
i tried to implement this feature but i couldn't due to my lack of php knowledge, 

-also btw i tried dev1.0.0 branch and its working flawlessly

**Comment by ghost** [comment]
i want to use your plugin in my server because your game is very unique im sure it will become the 1st loved game to the players

**Comment by ghost** [comment]
since ur not replying ill assume u don't receive notifications from closed issues , sorry but i will open a new issue for this.
