### ISSUE TITLE
Using players ID in player manager is not a good practice

### ISSUE THREAD

**Issue by Yexeed** [robske110/TicTacToe#3]
Because, when players rejoin, their ID is changing. So it will be really good to move to player names instead of IDs

**Comment by robske110** [comment]
This plugin doesn't use the ids for any saving stuff. It just uses them to identify a player in one session. After a player leaves, they get removed from the PlayerManager: https://github.com/robske110/TicTacToe/blob/master/TicTacToe/src/robske_110/TTT/EventListener.php#L91
I did find a small bug though while looking at the removal code...
